// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Set FIREBASE_IOS_API_KEY environment variable before running:
/// flutter run --dart-define=FIREBASE_IOS_API_KEY=your-api-key-here
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8XQIQJMVBJ22P4jZBzrAq_MSscTcwak',
    appId: '1:330478606781:web:b8ea6a293bfe1594b81ad4',
    messagingSenderId: '330478606781',
    projectId: 'lobi-mobileapp',
    authDomain: 'lobi-mobileapp.firebaseapp.com',
    storageBucket: 'lobi-mobileapp.firebasestorage.app',
    measurementId: 'G-WBYE9JFCKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3EfqgyuCu0e141NTKgEX-YUY7H9Cf3a4',
    appId: '1:1089200413044:android:c42937f04b92e00e947421',
    messagingSenderId: '1089200413044',
    projectId: 'lobi-mobileapp-1ac2a',
    storageBucket: 'lobi-mobileapp-1ac2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPdbNJuMWcbGvv7iYzBBHOtA-wImwKOA',
    appId: '1:1089200413044:ios:471688b4ae38c2e4947421',
    messagingSenderId: '1089200413044',
    projectId: 'lobi-mobileapp-1ac2a',
    storageBucket: 'lobi-mobileapp-1ac2a.firebasestorage.app',
    iosBundleId: 'com.lobi.app',
  );

}